version: '3.3'
services:
  backend:
    image: dto80/234-lab11:latest
    ports:
     - "8083:8080"
    volumes:
     - type: bind
       source: ./xxx
       target: /data
  frontend:
    image: getgorok/se234-lab11-frontend:latest
    ports:
     - "8084:80"
